# Generated by Django 3.0.4 on 2020-04-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cause', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('size', models.IntegerField()),
                ('desc', models.TextField()),
                ('link', models.CharField(max_length=100)),
            ],
        ),
    ]
